#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Anenth

# Short bio or description (displayed in the header)
description: Senior Front End Engineer

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: http://www.gravatar.com/avatar/a6433205a3eb9f458dcbd27d3ac2fa83.jpg?s=512
icon: http://www.gravatar.com/avatar/a6433205a3eb9f458dcbd27d3ac2fa83.jpg?s=25

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: anenthvishnu@gmail.com
  facebook: anenth
  flickr:
  github: anenth
  instagram:
  linkedin: anenthvishnu
  pinterest:
  rss: # just type anything here for a working RSS icon, make sure you set the "url" above!
  twitter: anenthv
  stackoverflow: users/2686105/anenth
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: +AnenthVishnu


# Your disqus shortname, entering this will enable commenting on posts
disqus: anenthv

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-43181096-1

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: anenth.js.org

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

markdown: redcarpet
redcarpet:
  extensions: [ "tables"]
highlighter: pygments
permalink: /:title/
# The release of Jekyll Now that you're using
version: v2.5.3

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - CNAME
